[ Network | Mail | News | FTP | Gopher | Finger | HTTP | HyperDocs ]

HyperDocTools.History *	Display the history of the marked document.
HyperDocs.ClearCache	Free all objects in the cache.
HyperDocTools.Fetch Local.Doc ~	Download the selected link to Local.Doc.
HyperDocTools.LinkIndex *	Display a listof all links in the marked docu

Desktops.OpenDoc HyperDocs.Panel	HyperDocs panel	
Desktops.OpenDoc HyperLinks.Panel	HyperLinks panel
