The Partition tool displays and modifies hard disk partition tables

Partition.Show	Display partition table(s)
Partition.Activate {num} ~	Make the listed partition(s) bootable
Partition.Check <num> ~	Check partition's sectors for readability
Partition.ChangeType <num> <from> <to>	Change partition type
Partition.Delete <num> <type>	Delete a primary partition
Partition.Create <num> <sizeMb>	Create a primary Oberon partition
Partition.Verbose ^ on off	Set state of verbose flag controlling output
