Snapshot.Viewer *	Make snapshot of viewer
Snapshot.Document *	Make snapshot of document
Snapshot.Gadget *	Make snapshot of marked gadget

Snapshot.InsertViewer *	Insert snapshot of viewer at caret
Snapshot.InsertDocument *	Insert snapshot of document at caret
Snapshot.InsertGadget *	Insert snapshot of marked gadget

Snapshot.Screen	Make snapshot of the screen

The snapshot tool is not supported by all display drivers
