[ System3 | Applications | Documentation ]

      
      
      

Desktops.OpenDoc ^  (or MM-MR)   Desktops.Open Oberon.Desk
	http://www.oberon.ethz.ch/native/	Native Oberon Home
	mailto:oberon@inf.ethz.ch	Oberon Helpline
	ftp://ftp.inf.ethz.ch/pub/Oberon/System3/	Official ftp site

	System.CopyFiles => ~
	System.RenameFiles => ~
	System.DeleteFiles ~

Script.Open System.Text
	click middle mouse button (or Ctrl) on 
	Script.Open above for introductory text

