Converter for Oberon V4 text files
to System 3 text documents (rs, adapted jm)

WTS can convert the fonts, parcs, pictures, stamps, folds,
and drawings of a V4 text to the appropriate gadget
in Oberon System 3. Parcs are converted to Text Gadget
styles.

WTS.Convert V4.Text ~	convert Text (removes Elems)
WTS.Convert V4.Text\s ~	convert Text (convert Elems)
WTS.Convert V4.Text\b ~	convert and make .Bak file

---
